### ISSUE TITLE
VS-shipped LLVM can't be detected

### ISSUE THREAD

**Issue by puhach** [mangh/llvm2019#2]
I am opening this issue since the extension is supposed to detect the CLang/LLVM provided with Visual Studio installation as well as the external one. 

The Clang compiler (from VS) is installed:
![Screenshot 2020-06-02 20 35 42](https://user-images.githubusercontent.com/12899171/83551249-c4eabf80-a510-11ea-9828-5a329d7dafbc.png)

_C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\x64\bin_ is added to PATH. 

No external LLVM tools are installed.

In Visual Studio create a new project. In the project properties set **Platform Toolset** to **LLVM**.
![Screenshot 2020-06-02 20 43 00_cr](https://user-images.githubusercontent.com/12899171/83552025-ccf72f00-a511-11ea-8806-7e5ee4bbcc4f.jpg)

Building fails with the following errors:
```
1>------ Build started: Project: ConsoleApplication1, Configuration: Debug x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(514,5): error MSB6004: The specified task executable location "bin\clang-cl.exe" is invalid.
1>Done building project "ConsoleApplication1.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by mangh** [comment]
Just provide the extension with the path(s) to the Clang/LLVM toolchain:

![image](https://user-images.githubusercontent.com/11795323/83611170-e7b4bc80-a580-11ea-88a1-95c5999496c5.png)

Et voilà:
```
1>------ Build started: Project: llvmtest, Configuration: Release x64 ------
1>Build started 03.06.2020 09:55:20.
1>Target InitializeBuildStatus:
1>  Creating "Release\llvmtest.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
1>Target Link:
1>  llvmtest.vcxproj -> C:\Users\Marek\source\repos\llvmtest\Release\llvmtest.exe
1>Target FinalizeBuildStatus:
1>  Deleting file "Release\llvmtest.tlog\unsuccessfulbuild".
1>  Touching "Release\llvmtest.tlog\llvmtest.lastbuildstate".
1>
1>Build succeeded.
1>    0 Warning(s)
1>    0 Error(s)
1>
1>Time Elapsed 00:00:00.52
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
Happy now?

**Comment by puhach** [comment]
Ok, thank you. I just expected the extension to detect it automatically (as it does for external LLVM).
